cnl-toolchain/src/main/java/cnltoolchain/CNLToolchain.java, conformance-checking/src/main/java/conformancecheck/api/IConformanceCheck.java, conformance-checking/src/main/java/conformancecheck/impl/ConformanceCheckImpl.java, conformance-checking/src/main/java/conformancecheck/impl/ConformanceCheckOntologyClassesAndProperties.java, owlify-famix/src/main/java/ontology/FamixOntClassesAndProperties.java, owlify-famix/src/main/java/ontology/FamixOntology.java, owlify-famix/src/main/java/parser/FamixOntologyTransformer.java, owlify-git/src/main/java/ontology/GitOntClassesAndProperties.java, owlify-git/src/main/java/scanner/GitOntologyTransformer.java, owlify-main/src/main/java/core/OwlifyComponent.java, owlify-maven/src/main/java/MavenOntClasses.java, owlify-maven/src/main/java/MavenPOMFileParser.java, rule-based-mapping/src/main/java/api/ExecuteMappingAPIImpl.java, rule-specification/src/main/java/asciidocparser/AsciiDocArc42Parser.java
The hard-coded OWL prefixes from the `conformancechecking-documentation` module have been replaced by a more flexible approach. Each module that provides some OWL namespace has a method to query them now, and the tool chain passes them to `conformancechecking-documentation`.
=> Issue #44 done

.github/workflows/build.yml, pom.xml
This change excludes a test, which only fails in the ci environment, but not locally.
To ensure that a local run of `mvn test` still executes all tests, a profile for the ci is created.
=> Exclude failing test in ci

cnl-toolchain/src/main/java/cnltoolchain/CNLToolchain.java, cnl-toolchain/src/main/java/cnltoolchain/CNLToolchainCLI.java, owlify-famix/src/main/java/parser/FamixOntologyTransformer.java, owlify-famix/src/test/java/parser/FamixOntologyTransformerTest.java, owlify-main/src/main/java/core/AbstractOwlifyComponent.java, owlify-main/src/main/java/core/OwlifyComponent.java, rule-specification/src/main/java/asciidocparser/AsciiDocArc42Parser.java, rule-specification/src/test/java/asciidocparser/AsciiDocArc42ParserTest.java
Replace the path, which is hold as string, with `java.nio.file.Path`.
This allows for understandable error checking on the rule and project path.
Also, this solves #83 .
=> Replace string with path

architecture-description-parser/pom.xml
This pull request updates the asciidoctorj dependency to avoid the following warning while executing the toolchain:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/Users/vhs/.m2/repository/com/headius/backport9/1.2/backport9-1.2.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
=> Update asciidoctorj to avoid warning

owlify-famix/src/main/java/org/archcnl/owlify/famix/codemodel/Method.java, owlify-famix/src/main/java/org/archcnl/owlify/famix/ontology/FamixOntology.java, owlify-famix/src/test/java/org/archcnl/owlify/famix/ontology/FamixOntologyTest.java
- using percent notation/uri encoding
- spaces are replaced by minus signs
closes #120
=> fixed use of restricted characters in famix uris

toolchain/src/main/java/org/archcnl/toolchain/CNLToolchain.java, toolchain/src/main/java/org/archcnl/toolchain/CNLToolchainCLI.java
A java project could consist of multiple source paths.
For example, ArchCNL itself consists of multiple maven modules.
Since the javaparser needs a path to the `src` directory to resolve all symbols, that would require multiple runs of ArchCNL to analyze its source if #113 would be implemented.
The solution this pull request provides is to add multiple source paths in one run. The `OwlifyComponent`-Interface already [uses a list of source paths](https://github.com/Mari-Wie/ArchCNL/blob/e5e816ffeb6dc7e2e0162ad3b13fac0869cbd4fc/owlify/src/main/java/org/archcnl/owlify/core/OwlifyComponent.java#L21), so it is only a matter of providing them from the cli.
=> Add multiple source paths

toolchain/src/main/java/org/archcnl/toolchain/CNLToolchainCLI.java
- closes #145
- sourcepaths argument's description now refers to all source paths and not just java ones
=> improved cli argument descriptions

java-parser/src/main/java/org/archcnl/javaparser/visitors/ThrowStatementVisitor.java, java-parser/src/test/java/org/archcnl/javaparser/visitors/ThrowStatementVisitorTest.java, java-parser/src/test/resources/examples/TryCatchThrow.java
Exceptions, that are not contained in the source folder that is passed to javaparser, would be considered external exceptions.
Javaparser can not solve their type if they are thrown or used as an argument.
But that should not stop the entire parsing process.
The solution, that is proposed here, is to catch these errors and log them. They are not added as type, since their type can not be resolved.
An example for such a problem are [some parts of the Corona-Warn-App](https://github.com/corona-warn-app/cwa-server/blob/6ba1b4750a8073063ae16cad91102a63b44932f8/services/distribution/src/main/java/app/coronawarn/server/services/distribution/statistics/file/RemoteStatisticJsonFileLoader.java#L61). But throwing an exception of a type that comes from an external library should not be too uncommon.
=> Catch errors thrown by javaparser on external exceptions

pom.xml
As @VincentRaudszus pointed out to me, the current surefire plugin is too old to detect and execute the JUnit 5 tests in the kotlin parser.
With this version, the seven tests in the kotlin parser are executed.
The result of `mvn verify --projects kotlin-parser -am`:
```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ kotlin-parser ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.archcnl.kotlinparser.visitor.KotlinTypeVisitorTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.137 s - in org.archcnl.kotlinparser.visitor.KotlinTypeVisitorTest
[INFO] Running org.archcnl.kotlinparser.visitor.ImportDeclarationVisitorTest
[INFO] …
```
=> Update surefire plugin to support JUnit 5

.github/workflows/build.yml, pom.xml
_Note: The CI pipeline failed due to the adjusted GitHub workflow. It should work once merged in the master branch (I tested it in my fork)._
- Added Jacoco plugin to test the test coverage as part of the CI pipeline. The plugin is currently set up to throw a warning when the branch coverage in any bundle / sub-project / module (whatever you want to call them) is below 90%. The pipeline will not fail because of this (we should change this once the 90% coverage goal is reached).
- In order to execute the Jacoco plugin the GitHub workflow needed to be adjusted as the plugin is only executed in the verify stage. This adjustment will not change the current functionality as the integration tests are manually excluded and the package command is executed as part of the maven verify command.
=> ARCHCNL-14: Pipeline should fail when coverage < 90%

.github/workflows/build.yml, pom.xml
After the latest changes to the CI pipeline (introduction of Jacoco to track coverage and changing the GitHub workflow from mvn package to mvn verify) the pipeline can no longer succeed outside the main branch as the spotless plugin is unable to find branch "origin/master" which it uses to make sure that only newly changed files are checked for format errors.
According to my research this bug was already present before the latest change but had no impact as spotless:check was never executed (by default it is executed in the verify phase which comes after the package phase. See https://github.com/diffplug/spotless/tree/master/plugin-maven#disabling-warnings-and-error-messages).
There are several options to fix this:
- Revert the maven command in the pipeline back to package. Problem: This …
=> Bugfix: Pipeline cannot succeed outside of master branch

pom.xml
[KotlinParser.g4](https://github.com/Mari-Wie/ArchCNL/blob/master/kotlin-parser/src/main/antlr4/org/archcnl/kotlinparser/grammar/KotlinParser.g4) is not truly a generated class. However, it was also not written specifically for this project and was taken from https://kotlinlang.org/docs/reference/grammar.html. Only a small part of its functionality is actually used and tested within ArchCNL. Ensuring the sufficient test coverage of this parser is thus not within the scope of this project and should not be taken into account for the coverage checks within the pipeline,
There are two more files from the same source that I chose not to exclude for the following reasons:
- [KotlinLexer.g4](https://github.com/Mari-Wie/ArchCNL/blob/master/kotlin-parser/src/main/antlr4/org/archcnl/kotlinparser/gr …
=> ARCHCNL-32: Generated classes excluded from coverage check in pipeline

toolchain/src/main/java/org/archcnl/toolchain/CNLToolchain.java
In the context of #176 there could be a problem, where the size of the list of violations is unequal to the size of the rules.
Since the violations are accessed by the rule index, this can lead to a problem, where the rule index is higher than the size of the list of violations. This will lead to "Index out of Bounds".
This pull request tries to mitigate this, by limiting the access thought the list size and takes an empty list otherwise.
=> Do not access violation at an index that is greater than the list size

architecture-description-parser/src/main/java/org/archcnl/architecturedescriptionparser/CNLTranslator.java, org.architecture.cnl.parent/org.architecture.cnl/src/main/java/org/architecture/cnl/CNL2OWLGenerator.java, org.architecture.cnl.parent/org.architecture.cnl/src/main/java/org/architecture/cnl/generator/ArchcnlGenerator.java, owl-creator/src/main/java/org/archcnl/owlcreator/api/OntologyAPI.java, owl-creator/src/main/java/org/archcnl/owlcreator/impl/OWLAPIImpl.java, toolchain/src/main/java/org/archcnl/toolchain/CNLToolchain.java
I added re-throwing of caught exceptions and added propagation until execute(...) is reached.
In the path to execute there was a section where I could not add throws IOException to a function
since it was an overloaded function from another library. Here I used UncheckedIOExceptions to
pass the exception further up.
Questions:
Is logging fine as it is?
Is the usage of UncheckedIOException a problem?
=> added handling and propagation of exceptions in OWLAPIImpl

web-ui/src/main/java/org/vaadin/example/queryview/WhereTextBoxesLayout.java
Pausing a row dow greys out the textfields.
The plus button remains active so that users can add more query rows without having to unpause the first row. 
Since every row only needs a delete (minus button), it may be better to have only a single plus button (above or below the rows)
which adds new rows. But that is not subject to this ticket. 
I've also added a small tooltip for the pausebutton. This tooltip changes depending on whether the row is active or not.
=> Grey out query row (Feature/archcnl 62)

web-ui/src/main/java/org/vaadin/example/queryview/WhereTextBoxesLayout.java
Reopened PR from @cmkehler as I had to revert the previous merge since it contained format violations.
Pausing a row dow greys out the textfields.
The plus button remains active so that users can add more query rows without having to unpause the first row.
Since every row only needs a delete (minus button), it may be better to have only a single plus button (above or below the rows)
which adds new rows. But that is not subject to this ticket.
I've also added a small tooltip for the pausebutton. This tooltip changes depending on whether the row is active or not.
=> Feature/archcnl 62/grey out query row

web-ui/architecture-rules.adoc
These mappings and rules can be used to check whether the chosen flavor of the MVP pattern is used correctly in the web-ui module.
One additional mapping that would be nice to have but does not seem to work as of now is the following one with its recursive definition:
```
[role="mapping"]
inheritFromRecursiveMapping: (?subClass architecture:inheritFrom ?superClass) -> (?subClass architecture:inheritFromRecursive ?superClass)
[role="mapping"]
inheritFromRecursiveMapping: (?subClass architecture:inheritFromRecursive ?superClass) (?subsubClass architecture:inheritFrom ?subClass) -> (?subsubClass architecture:inheritFromRecursive ?superClass)
```
This mapping could be used to make rules for all classes that inherit from Vaadin's Component class.
=> Basic Rules and Mappings for Web-UI module

web-ui/src/main/java/org/archcnl/domain/input/model/mappings/Concept.java, web-ui/src/main/java/org/archcnl/domain/input/model/mappings/ConceptManager.java, web-ui/src/main/java/org/archcnl/domain/input/model/mappings/Relation.java, web-ui/src/main/java/org/archcnl/domain/input/model/mappings/RelationManager.java, web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/ConceptEditorPresenter.java, web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/MappingEditorContract.java, web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/MappingEditorView.java, web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/RelationEditorPresenter.java
Previously the lists would only update after creating a new concept or a new relation.
=> Concept/Relation List now update with every change

web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/MappingEditorView.java
- Previously there was a spelling mistake in that text
- The inclusion of"Concept" and "Relation" in the text is not necessary as the constructor parameter `mappingType` holds just the right string for that purpose
- I thought the "What does this Concept represent?" placeholder text might be a better incentive for the user to enter a fitting description
=> Placeholder text of description TextField changed

pom.xml
The currently used version of log4j contained a critical vulnerability (see https://www.kaspersky.com/blog/log4shell-critical-vulnerability-in-apache-log4j/43124/). This PR updates log4j to the recommended version.
=> Update log4j to recommended version

web-ui/src/main/java/org/archcnl/domain/input/io/ArchRulesFromAdocReader.java, web-ui/src/main/java/org/archcnl/domain/input/io/ArchRulesToAdocWriter.java, web-ui/src/test/java/org/archcnl/domain/TestUtils.java, web-ui/src/test/java/org/archcnl/domain/input/io/ArchRuleToAdocWriterTest.java, web-ui/src/test/java/org/archcnl/domain/input/io/ArchRulesFromAdocReaderTest.java, web-ui/src/test/resources/ReaderParsingTest.adoc, web-ui/src/test/resources/architecture-documentation.adoc
Descriptions in the adoc file are written like this:
[role="description"]
Every class whose name ends with Aggregate is an Aggregate.
[role="mapping"]
isAggregate: (?class rdf:type famix:FamixClass) (?class famix:hasName ?name) regex(?name, '(\\w||\\W)*\\.(\\w||\\W)*Aggregate') -> (?class rdf:type architecture:Aggregate)
Descriptions should only contain alphanumeric characters, spaces and punctuation marks (.) and be contained in a single line.
I noticed the resideIn Mapping does not get imported to the GUI. Is this supposed to be like this? This happens on master aswell.
=> Feature/arch cnl 129/description exporter importer

web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/AndTripletsEditorPresenter.java, web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/AndTripletsEditorView.java, web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/triplet/ObjectView.java, web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/triplet/TripletView.java
Readded the label functionality.  The labels "Subject", "Predicate" and "Object" now appear above the first tripletView in the orBlock.
Fixed a bug created with the mappingeditor rework that allowed the last tripletView to be deleted without creating a new one.
=> Enhancement/archcnl 111/or block labels2

web-ui/src/main/java/org/archcnl/ui/MainPresenter.java, web-ui/src/main/java/org/archcnl/ui/menudialog/SelectDirectoryDialog.java
- Relating to implementation of #265 
- Noticed that it runs, even when cancel is pressed. This is fixed now.
=> Only run check if open button was pressed

conformance-checking/src/main/java/org/archcnl/conformancechecking/impl/ConformanceCheckOntologyClassesAndProperties.java, stardog-wrapper/src/main/java/org/archcnl/stardogwrapper/api/StardogDatabaseAPI.java, stardog-wrapper/src/main/java/org/archcnl/stardogwrapper/impl/StardogDatabase.java, toolchain/src/integration-test/java/org/archcnl/toolchain/ToolchainIT.java, toolchain/src/main/java/org/archcnl/toolchain/CNLToolchain.java, web-ui/src/main/resources/queries/violationsSubjectPredicateObject.sparql
- Custom namespaces have been added to the database (Famix, Architecture, Conformance)
- Just with these namespaces queries where still not formated as they are when calling the same query from stardog studio. They should be in the prefix format, e.g.; famix:#FamixClass...
- There was no apparent way to directly do this, so now the results get manually shortened by any prefixes that they contain
=> Feature/arch cnl 158/add namespaces to ontology

web-ui/src/main/java/org/archcnl/ui/MainPresenter.java
Running the architecture check now checks for any exceptions (not just the expected ones) so that no sensitive information might get exposed
=> Catch any exception in pipeline to not expose sensitive information

web-ui/src/main/java/org/archcnl/ui/inputview/rulesormappingeditorview/architectureruleeditor/RuleCreatorView.java
Fixed bug where an unnecessary period would get added after editing a rule.
Periods now only get added if the rule doesn't end in a period.
=> Fixed bug where an unnecessary period would get added after editing a rule.

web-ui/src/main/java/org/archcnl/ui/outputview/queryviews/components/Violation.java
Make sure that no special URI characters (like %28) are shown in result tables.
=> Decode URIs to achieve a cleaner presentation in GUI

web-ui/src/main/java/org/archcnl/domain/output/model/query/QueryUtils.java, web-ui/src/main/java/org/archcnl/ui/MainPresenter.java, web-ui/src/main/java/org/archcnl/ui/outputview/OutputPresenter.java, web-ui/src/main/java/org/archcnl/ui/outputview/OutputView.java, web-ui/src/main/java/org/archcnl/ui/outputview/queryviews/PredefinedQueryComponent.java, web-ui/src/main/resources/queries/minimalisticViolatingInstances.sparql
- In the general information tab the user is now presented with the minimalistic query appended by the location
- The query results table is placed above the query text for predefined queries just like for the default query
- All predefined queries are auto-executed together with the default query
=> Reorder and auto-run all predefined queries

web-ui/src/main/java/org/archcnl/domain/common/RelationManager.java, web-ui/src/main/java/org/archcnl/domain/common/VariableManager.java, web-ui/src/main/java/org/archcnl/domain/common/conceptsandrelations/CustomRelation.java, web-ui/src/main/java/org/archcnl/domain/common/io/importhelper/MappingParser.java, web-ui/src/main/java/org/archcnl/domain/input/model/presets/microservicearchitecture/MicroserviceArchitectureTemplateManager.java, web-ui/src/main/java/org/archcnl/ui/MainPresenter.java, web-ui/src/main/java/org/archcnl/ui/common/andtriplets/AndTripletsEditorPresenter.java, web-ui/src/main/java/org/archcnl/ui/common/andtriplets/triplet/events/PredicateSelectedEvent.java, web-ui/src/main/java/org/archcnl/ui/common/andtriplets/triplet/events/VariableSelectedEvent.java, web-ui/src/main/java/org/archcnl/ui/inputview/InputPresenter.java, web-ui/src/main/java/org/archcnl/ui/inputview/rulesormappingeditorview/mappingeditor/MappingEditorPresenter.java, web-ui/src/main/java/org/archcnl/ui/inputview/rulesormappingeditorview/mappingeditor/relationeditor/RelationEditorPresenter.java, web-ui/src/main/java/org/archcnl/ui/inputview/rulesormappingeditorview/mappingeditor/relationeditor/events/AddCustomRelationRequestedEvent.java, web-ui/src/main/java/org/archcnl/ui/outputview/OutputPresenter.java, web-ui/src/main/java/org/archcnl/ui/outputview/queryviews/CustomQueryPresenter.java, web-ui/src/test/java/org/archcnl/domain/TestUtils.java, web-ui/src/test/java/org/archcnl/domain/common/RelationManagerTest.java, web-ui/src/test/java/org/archcnl/domain/common/VariableManagerTest.java
This fixes a previous limitation of the type checker. See this example (Aggregate is one of the concepts from the OnionArchitectureDemo):
`(?a rdf:type architecture:Aggregate)
(?a famix:hasName ?name)`
Previously, these triplets would have resulted in a "Potential Type conflict" as hasName is defined on FamixClass and not on Aggregate. Now the type checker figures out that Aggregate is defined as a sub-type of FamixClass in its mapping and thus hasName is also defined for it. No type conflicts are reported in the GUI.
=> Type checker looks recursively for super types

web-ui/src/main/java/org/archcnl/domain/common/RelationManager.java
I noticed that some very important concepts that are in fact part of NamedEntity in the ontology were missing from the list of allowed subject types. I suspect there might be quite a few more missing subject/object types in the GUI.
=> Missing NamedEntiy subject types added

web-ui/src/main/java/org/archcnl/ui/common/conceptandrelationlistview/HierarchyView.java, web-ui/src/main/java/org/archcnl/ui/inputview/rulesormappingeditorview/RulesOrMappingEditorView.java, web-ui/src/main/java/org/archcnl/ui/inputview/rulesormappingeditorview/architectureruleeditor/RulesWidget.java
In PR #313 the superclass of the RuleWidget (responsible for displaying the list of architecture rules and linking to the RuleCreatorView was changed in order to be reused in the HierarchyView. However, this change removed the header from the RulesWidget making it impossible to access the RuleCreatorView.
This PR does the following:
- Undo the changes to RulesOrMappingEditorView and RuleWidget in order to reactivate the header.
- Move the HierarchyView specific code introduced in #313 to the RulesOrMappingEditorView directly into HierarchyView. HierarchyView was never supposed to be a subclass of RulesOrMappingEditorView in the first place as the name suggests.
=> Reactive header of RuleWidget
