Mari-Wie/ArchCNL

owlify-maven/src/main/java/MavenOntClasses.java

OWL Prefixes made final

---

SPARQL-Queries/0-test.sparql
SPARQL-Queries/violations.sparql
StardogConnector/src/main/java/impl/StardogICVAPIImpl.java
cnl-toolchain/src/main/java/cnltoolchain/CNLToolchain.java
common/src/main/java/datatypes/ArchitectureRule.java
common/src/test/java/common/ArchitectureRuleTest.java
conformance-checking/src/test/java/conformancecheck/api/CheckedRuleTest.java
conformance-checking/src/test/java/conformancecheck/impl/ConformanceCheckImplTest.java
jena-api/src/main/java/api/OWLAPIImpl.java
jena-api/src/main/java/api/OntologyAPI.java
jena-api/src/test/java/OWLAPIImplTest.java
org.architecture.cnl.parent/org.architecture.cnl/src/main/java/org/architecture/cnl/CNL2OWLGenerator.java
org.architecture.cnl.parent/org.architecture.cnl/src/main/java/org/architecture/cnl/RuleTypeStorageSingleton.java
org.architecture.cnl.parent/org.architecture.cnl/src/main/java/org/architecture/cnl/generator/ArchcnlGenerator.xtend
owlify-famix/src/main/java/visitors/AccessVisitor.java
owlify-famix/src/test/java/examples/TestClassA.java
owlify-git/src/main/java/model/GitCommit.java
owlify-git/src/main/java/ontology/GitOntClassesAndProperties.java
owlify-git/src/main/java/scanner/GitOntologyTransformer.java
rule-based-mapping/src/main/java/api/ExecuteMappingAPI.java
rule-based-mapping/src/main/java/api/ExecuteMappingAPIImpl.java
rule-based-mapping/src/main/java/api/ReasoningConfiguration.java
rule-based-mapping/src/test/java/api/ExecuteMappingAPIImplTest.java
rule-specification/src/main/java/asciidocparser/AsciiDocArc42Parser.java

Removed code duplications, extracted methods, resolved TODOs + other small refactorings.
Closes #63.

Refactorings

---

cnl-toolchain/src/main/java/cnltoolchain/CNLToolchain.java
cnl-toolchain/src/main/java/cnltoolchain/CNLToolchainCLI.java
cnl-toolchain/src/main/resources/log4j2.xml
pom.xml

Update log4j and use `log4j-slf4j-impl` to capture slf4j logging output by libraries.
Add a verbose mode for console and file logging.

Refine logging

---

owlify-famix/src/main/java/org/archcnl/owlify/famix/ontology/FamixOntology.java
owlify-famix/src/main/java/org/archcnl/owlify/famix/visitors/DeclaredJavaTypeVisitor.java
owlify-famix/src/main/java/org/archcnl/owlify/famix/visitors/ThrowStatementVisitor.java
owlify-famix/src/test/java/examples/ExampleClassWithExceptions.java
owlify-famix/src/test/java/org/archcnl/owlify/famix/visitors/ThrowStatementVisitorTest.java

the following syntax is also supported now:
```Java
Exception e = new Exception();
throw e;
```
Closes #78

implemented TODO in ThrowStatementVistor

---

java-parser/src/test/java/org/archcnl/javaparser/parser/ModelExtractorTest.java

I have add a test for the case classB.
If you see anything wrong, please tell me.

test for classB

---

java-parser/src/main/java/org/archcnl/javaparser/parser/JavaOntologyTransformer.java
kotlin-parser/src/main/java/org/archcnl/kotlinparser/parser/KotlinOntologyTransformer.java
org.architecture.cnl.parent/org.architecture.cnl/.classpath
owlify-famix/src/main/java/org/archcnl/owlify/famix/ontology/FamixOntologyTransformer.java

- new abstract base class for XyzOntologyTransformers
- changed JavaOntologyTransformer to extend the new class
- changed KotlinOntologyTransformer to extend the new class
- closes #141 
- closes #142

removed code duplication from parsers

---

org.architecture.cnl.parent/org.architecture.cnl/src/main/java/org/architecture/cnl/generator/ArchcnlGenerator.java

The control flow is nearly the same as in ArchcnlGeneratorXtend.old

refactor: Improve readability of compile method for NegationRuleType

---

java-parser/src/test/java/org/archcnl/javaparser/visitors/ConstructorDeclarationVisitorTest.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/GenericVisitorTest.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/ImportDeclarationVisitorTest.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/JavaFieldVisitorTest.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/JavaTypeVisitorTest.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/MethodDeclarationVisitorTest.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/NamespaceVisitorTest.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/ThrowStatementVisitorTest.java

Remove duplicate init method in visitors tests

refactor: issue 133 reduce duplicates in visitors tests

---

toolchain/src/main/java/org/archcnl/toolchain/CNLToolchain.java
toolchain/src/main/java/org/archcnl/toolchain/CNLToolchainCLI.java

Allow user to select enabled parsers

---

conformance-checking/src/main/java/org/archcnl/conformancechecking/impl/ConformanceCheckOntology.java
conformance-checking/src/main/java/org/archcnl/conformancechecking/impl/ConformanceCheckOntologyClassesAndProperties.java

- Closes #130
- Implemented the object properties part of the Ontology Enumeration Pattern for the conformance check ontology
- Adapted method outdated method calls to call the new factory method
- Renamed constant according to Google style guide

Ontology Enumeration Pattern for the conformance checking ontology III (Object Properties) implemented #130

---

stardog-wrapper/src/main/java/org/archcnl/stardogwrapper/api/exceptions/MissingBuilderArgumentException.java
stardog-wrapper/src/main/java/org/archcnl/stardogwrapper/impl/StardogDatabase.java

removed dead code in stardog-wrapper

---

java-parser/src/main/java/org/archcnl/javaparser/visitors/LocalVariableVisitor.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/LocalVariableVisitorTest.java
owlify-famix/src/main/java/org/archcnl/owlify/famix/codemodel/LocalVariable.java
owlify-famix/src/test/java/org/archcnl/owlify/famix/codemodel/DummyObjects.java
owlify-famix/src/test/java/org/archcnl/owlify/famix/codemodel/LocalVariableTest.java
owlify-famix/src/test/java/org/archcnl/owlify/famix/codemodel/MethodTest.java

- Added modifiers to the ontology of local variables
- Added/Adjusted the relevant tests
- closes #127

Local variables modifier

---

.gitignore
pom.xml
stardog-wrapper/src/main/java/org/archcnl/stardogwrapper/api/StardogDatabaseAPI.java
toolchain/src/integration-test/java/org/archcnl/toolchain/ToolchainIT.java
toolchain/src/integration-test/resources/OnionArchitectureDemo/LICENSE
toolchain/src/integration-test/resources/OnionArchitectureDemo/README.md
toolchain/src/integration-test/resources/OnionArchitectureDemo/rules.adoc
toolchain/src/integration-test/resources/OnionArchitectureDemo/src/api/UserService.java
toolchain/src/integration-test/resources/OnionArchitectureDemo/src/api/ValidationAggregate.java
toolchain/src/integration-test/resources/OnionArchitectureDemo/src/domain/User.java
toolchain/src/integration-test/resources/OnionArchitectureDemo/src/domain/UserAggregate.java
toolchain/src/integration-test/resources/queries/firstRuleViolated.sparql
toolchain/src/integration-test/resources/queries/secondRuleViolated.sparql

- set up Maven failsafe plugin for integration testing (IT)
- set up Maven goals to include */src/integration-test/java and */src/integration-test/resources subdirectories
- added OnionArchitectureDemo project as a test resource
- added an integration test which executes the toolchain on the demo project and checks that both violations are found
- IT is not yet set up in the CI pipeline, because the CI server needs a valid stardog license
- closes #99

added integration tests

---

java-parser/src/main/java/org/archcnl/javaparser/visitors/NormalAnnotationExpressionVisitor.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/MethodDeclarationVisitorTest.java
java-parser/src/test/java/org/archcnl/javaparser/visitors/NormalAnnotationVisitorTest.java
java-parser/src/test/resources/examples/ComplexClass.java

added unit test for NormalAnnotationExpressionVisitor

---

conformance-checking/src/main/resources/ontologies/architectureconformance.owl
conformance-checking/src/test/java/org/archcnl/conformancechecking/api/CheckedRuleTest.java
conformance-checking/src/test/java/org/archcnl/conformancechecking/impl/ConformanceCheckImplTest.java
conformance-checking/src/test/java/org/archcnl/conformancechecking/impl/ConformanceCheckOntologyClassesAndPropertiesTest.java
conformance-checking/src/test/java/org/archcnl/conformancechecking/impl/ConformanceCheckOntologyTest.java
conformance-checking/src/test/resources/architecture-rule-expected.owl

Add tests for ConformanceCheckOntology
Renamed tests according to given-when-then pattern

ARCHCNL-7: Improved test coverage in conformance-checking

---

web-ui/src/main/java/org/vaadin/example/queryview/WhereTextBoxesLayout.java

Revert "Grey out query row (Feature/archcnl 62)"

---

owlify-famix/src/main/java/org/archcnl/owlify/famix/ontology/FamixOntology.java
owlify-famix/src/test/java/org/archcnl/owlify/famix/ontology/FamixOntologyTest.java

New line characters are not necessarily a problem, but they create unnecessary spam in the log and would not exist in a proper URI.

Replace new line characters in URI

---

web-ui/src/main/java/org/archcnl/ui/input/InputView.java
web-ui/src/main/java/org/archcnl/ui/input/ruleeditor/ArchitectureRulesContract.java
web-ui/src/main/java/org/archcnl/ui/input/ruleeditor/ArchitectureRulesLayout.java
web-ui/src/main/java/org/archcnl/ui/input/ruleeditor/NewArchitectureRulePresenter.java
web-ui/src/main/java/org/archcnl/ui/input/ruleeditor/NewArchitectureRuleView.java

Added a simple GUI to add new ArchitectureRules via an TextArea; to be expanded in the future.
The rules will get added to the ArchitectureRuleManager, but aren't checked for correctness yet.
I will add a presenter to NewArchitectureRuleView.java on request (I am unsure if one is necessary in this case)

Feature/archcnl 68/simple architecture GUI

---

web-ui/src/main/java/org/archcnl/domain/input/model/mappings/Concept.java
web-ui/src/main/java/org/archcnl/domain/input/model/mappings/CustomConcept.java
web-ui/src/main/java/org/archcnl/domain/input/model/mappings/CustomRelation.java
web-ui/src/main/java/org/archcnl/domain/input/model/mappings/Relation.java
web-ui/src/main/java/org/archcnl/ui/input/ConceptAndRelationView.java
web-ui/src/main/java/org/archcnl/ui/input/ConceptListEntry.java
web-ui/src/main/java/org/archcnl/ui/input/MappingListEntry.java
web-ui/src/main/java/org/archcnl/ui/input/MappingListEntryLayout.java
web-ui/src/main/java/org/archcnl/ui/input/MappingListLayout.java
web-ui/src/main/java/org/archcnl/ui/input/RelationListEntry.java
web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/ConceptEditorPresenter.java
web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/MappingEditorContract.java
web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/MappingEditorView.java
web-ui/src/main/java/org/archcnl/ui/input/mappingeditor/RelationEditorPresenter.java

Added Descriptions + Tooltip for Concepts and Relations

Feature/archcnl 75/infofield

---

web-ui/Dockerfile
web-ui/docker/README.md
web-ui/docker/docker-compose-browser.yml
web-ui/docker/docker-compose.yml
web-ui/pom.xml
web-ui/src/main/java/org/archcnl/application/Application.java
web-ui/src/main/java/org/archcnl/application/service/ConfigAppService.java
web-ui/src/main/java/org/archcnl/ui/main/MainPresenter.java
web-ui/src/main/java/org/archcnl/ui/main/MainView.java
web-ui/src/main/java/org/archcnl/ui/output/component/AbstractQueryResultsComponent.java
web-ui/src/main/java/org/archcnl/ui/output/component/CustomQueryUiComponent.java
web-ui/src/main/java/org/archcnl/ui/output/component/FreeTextQueryUiComponent.java
web-ui/src/main/java/org/archcnl/ui/output/component/GridView.java
web-ui/src/main/java/org/archcnl/ui/output/component/QueryResultsUiComponent.java
web-ui/src/main/java/org/archcnl/ui/output/component/QueryView.java
web-ui/src/main/resources/db.properties
web-ui/src/test/resources/db.properties

The whole ArchCNL program is provided as a Docker Image with Stardog as a Docker-Compose.

ARCHCNL-113: Config docker and docker compose

---

web-ui/src/main/java/org/archcnl/domain/input/io/ArchRulesFromAdocReader.java
web-ui/src/test/java/org/archcnl/domain/input/io/ArchRulesFromAdocReaderTest.java
web-ui/src/test/resources/EndToEndTest.adoc
web-ui/src/test/resources/WriterTest.adoc

Compliments #246 with added testing of descriptions for the AdocReader

Add testing of descriptions to AdocReaderTest

---

web-ui/src/main/java/org/archcnl/domain/common/ConceptManager.java
web-ui/src/main/java/org/archcnl/domain/common/RelationManager.java

Added descriptions to some concepts and relations in the GUI

---

web-ui/src/main/java/org/archcnl/domain/common/HierarchyManager.java

Fixed root nodes in the hierarchies causing crashes when moving them

Hierarchy fix/fix crash when root is moved

---

toolchain/src/integration-test/resources/queries/firstRuleCorrectlyMapped.sparql
web-ui/src/main/java/org/archcnl/domain/output/model/query/QueryUtils.java
web-ui/src/main/java/org/archcnl/ui/outputview/OutputPresenter.java
web-ui/src/main/java/org/archcnl/ui/outputview/OutputView.java
web-ui/src/main/java/org/archcnl/ui/outputview/queryviews/QueryResultsComponent.java
web-ui/src/main/java/org/archcnl/ui/outputview/queryviews/components/GeneralInfoLayout.java
web-ui/src/main/resources/queries/nrOfPackages.sparql
web-ui/src/main/resources/queries/nrOfRelationships.sparql
web-ui/src/main/resources/queries/nrOfTypes.sparql
web-ui/src/main/resources/queries/nrOfViolations.sparql

Queries have been added that get the required information from the database and add it to the GeneralInformationLayout

Feature/arch cnl 164/add general information layout information

---

web-ui/src/main/java/org/archcnl/domain/common/RelationManager.java

I made the description of the relation easier to understand so the possible subject and object types can be easily deducted.

Improved description of matches relation
